# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:
  - os: linux
    env:
      - PYTHON_VER='3.5'
  - os: linux
    env:
      - PYTHON_VER='2.7'

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n p4env python=$PYTHON_VER ci-psi4 psi4 scipy lawrap -c psi4/label/dev -c psi4
  - source activate p4env
  - conda install cmake
  - conda list

# Install various required modules
  - pip install --upgrade pip setuptools
  - pip install pytest pytest-cov
  - pip install codecov

# Build the C++
  - python setup.py cmake

# Install the plugin locally
  - pip install -e .

before_script:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - python -c 'import numpy; print(numpy.version.version)'

script:
  - py.test -v --cov=./

notifications:
    email: false

after_success:
  - codecov
